services:
  app:
    build:
      target: "prod"
    image: "transcriptor"
    ports:
      - 8000:8000
    env_file: ".env"
  redis:
    image: redis:latest
    restart: always
    env_file: ".env"
    ports:
      - 6379:6379
