# fly.toml app configuration file generated for transcriptor-nameless-meadow-59 on 2023-12-20T02:42:44-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "transcriptor-nameless-meadow-59"
primary_region = "scl"

[build]
  build-target = "prod"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
