create table
  public.profiles (
    id bigint generated by default as identity,
    created_at timestamp with time zone null default now(),
    updated_at timestamp with time zone null default now(),
    full_name character varying null,
    avatar_url character varying null,
    user_id uuid not null,
    constraint profiles_pkey primary key (id),
    constraint profiles_user_id_key unique (user_id),
    constraint profiles_user_id_fkey foreign key (user_id) references auth.users (id) on update cascade on delete cascade
  ) tablespace pg_default;
